#!/usr/bin/env bash
build-domain(){ #Serial,IP,Domain
	N=$4
	D=${N}.
	F=domains/$N
	SOA="1200 180 2419200 1200" # Refresh,Retry,Expire,TTL

	echo "@ IN SOA	$D ${D}benjamincook.ca. ( $2 $SOA )" >$F
	echo "@ IN NS		$D" >>$F
	echo "@ IN NS		bed.ac." >>$F
	echo "@ IN A		$3" >>$F
	if [[ $1 =~ v ]] ; then #virtual hosts
		build-subdomain "${@:5}"
	else
		echo "* IN CNAME	$D" >>$F
	fi
	if [[ $1 =~ m ]] ; then #SPF mail records
		echo "@ IN MX	10	$D" >>$F
		echo "$D IN TXT \"v=spf1 a mx -all\"" >>$F
		echo "$D IN SPF \"v=spf1 a mx -all\"" >>$F
	fi
}
build-subdomain(){
	if [[ -n $1 && -n $2 ]] ; then
		echo "$2	IN A	$1" >>$F
		build-subdomain "${@:3}"
	fi
}
build-domains(){
	ANNUMINAS=142.91.92.200
	EDHELLOND=174.37.137.139
	GONDOLIN=70.77.240.33
	MITHLOND=142.4.212.110
	MENEGROTH=174.137.52.197
	OSGILIATH=94.242.209.186

	MITHLONDA=192.50.242.72
	MITHLONDB=192.50.242.73
	MITHLONDC=192.50.242.74
	MITHLONDD=192.50.242.75
	mkdir -p domains
	build-domain v	6	$MITHLONDB	ennorath.ca \
		$ANNUMINAS annuminas \
		$EDHELLOND edhellond \
		$GONDOLIN gondolin \
		$MITHLOND mithlond \
		$MENEGROTH menegroth \
		$OSGILIATH osgiliath
	build-domain -	12	$MITHLOND	bed.ac
	build-domain -	3	$MITHLOND	blaze.im
	build-domain -	3	$MITHLOND	baryon.it
	build-domain -	2	$MITHLOND	cuntoso.com
	build-domain -	12 $MITHLOND	cupe399.ca
	build-domain -	4	$MITHLONDA	pgbass.com
	build-domain -	1	$MITHLONDC	hotin.pink
	build-domain - 13	$MITHLONDD	per.ninja	
	build-domain -	7	$MENEGROTH	psylight.ca	
	build-domain -	10	$MENEGROTH	baryon.ca
	build-domain -	2	$MENEGROTH	fb2k.net
	build-domain -	3	$MENEGROTH	hopesanddreamschildcare.ca
	build-domain m	4	$EDHELLOND	thegreenplace.ca	
	build-domain m	13	$EDHELLOND	benjamincook.ca
	build-domain -	1	$GONDOLIN	anaphor.net
	build-domain -	2	$ANNUMINAS	canar.moe	
	build-domain -	1	$ANNUMINAS	grimory.com
	build-domain -	1	$OSGILIATH	protoni.ca
}
make-conf(){
	for f in $(ls -1 domains) ; do
		echo-zone $f
	done > bind.conf.zones
}
echo-zone(){
	echo "zone \"$1\" {"
	echo "	type master;"
	echo "	file \"/etc/bind/domains/$1\"\;"
	echo "};"
}
refresh(){
	build-domains
	make-conf
	/etc/init.d/bind9 reload
}
eval "$@"
